/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYOBJECTAPIADAPTOR_H
#define MYOBJECTAPIADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.example
 */
class ExampleAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.example")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.example\">\n"
"    <property access=\"read\" type=\"b\" name=\"locked\"/>\n"
"    <method name=\"someMethod\"/>\n"
"    <method name=\"isLocked\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ExampleAdaptor(QObject *parent);
    virtual ~ExampleAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool locked READ locked)
    bool locked() const;

public Q_SLOTS: // METHODS
    bool isLocked();
    void someMethod();
Q_SIGNALS: // SIGNALS
};

#endif
