/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "myobjectapiadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ExampleAdaptor
 */

ExampleAdaptor::ExampleAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ExampleAdaptor::~ExampleAdaptor()
{
    // destructor
}

bool ExampleAdaptor::locked() const
{
    // get the value of property locked
    return qvariant_cast< bool >(parent()->property("locked"));
}

bool ExampleAdaptor::isLocked()
{
    // handle method call org.example.isLocked
    bool out0;
    QMetaObject::invokeMethod(parent(), "isLocked", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ExampleAdaptor::someMethod()
{
    // handle method call org.example.someMethod
    QMetaObject::invokeMethod(parent(), "someMethod");
}

